adapter_name_or_path: saves/GLM-4-0414-9B-Chat/lora/train_2025-10-17-20-02-53
cutoff_len: 8000
dataset_dir: LLaMA-Factory/data
ddp_timeout: 180000000
do_predict: true
double_quantization: true
eval_dataset: weibo_covid_RAG
finetuning_type: lora
flash_attn: auto
max_new_tokens: 512
max_samples: 100000
model_name_or_path: /root/autodl-fs/unsloth/GLM-4-9B-0414
output_dir: saves/GLM-4-0414-9B-Chat/lora/eval_2025-10-18-04-43-30
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
quantization_bit: 4
quantization_method: bnb
report_to: none
stage: sft
temperature: 0.95
template: glm4
top_p: 0.7
trust_remote_code: true
use_unsloth: true
