cutoff_len: 8000
dataset_dir: LLaMA-Factory/data
ddp_timeout: 180000000
do_predict: true
eval_dataset: weibo_covid_RAG
finetuning_type: lora
flash_attn: auto
max_new_tokens: 64
max_samples: 100000
model_name_or_path: /root/autodl-tmp/unsloth/DeepSeek-R1-0528-Qwen3-8B
output_dir: saves/DeepSeek-R1-0528-8B-Distill/lora/eval_2025-10-18-05-34-47
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
quantization_method: bnb
report_to: none
stage: sft
temperature: 0.95
template: deepseekr1
top_p: 0.7
trust_remote_code: true
use_unsloth: true
