adapter_name_or_path: saves/Llama-3-8B-Instruct/lora/train_2025-08-25-16-03-07
cutoff_len: 8000
dataset_dir: /root/LLaMA-Factory/data
do_predict: true
eval_dataset: weibo_covid_RAG
finetuning_type: lora
flash_attn: auto
max_new_tokens: 512
max_samples: 100000
model_name_or_path: /root/autodl-tmp/LLM-Research/Meta-Llama-3-8B-Instruct
output_dir: saves/Llama-3-8B-Instruct/lora/eval_2025-08-26-17-51-15
per_device_eval_batch_size: 1
predict_with_generate: true
preprocessing_num_workers: 16
quantization_bit: 4
quantization_method: bitsandbytes
stage: sft
temperature: 0.95
template: llama3
top_p: 0.7
